### ISSUE TITLE
请问训练完成后如何进行detection

### ISSUE THREAD

**Issue by YunLongPan** [ZeroE04/R-CenterNet#12]
win10，显卡2080s，train.py训练正常，训练完成后运行predict出现错误。
Traceback (most recent call last):
  File "D:/R-CenterNet-master/predict.py", line 237, in <module>
    output, dets, forward_time = process(images, return_time=True)
  File "D:/R-CenterNet-master/predict.py", line 152, in process
    output = model(images)
  File "D:\Anaconda\envs\CenterNet2\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "./backbone\dlanet.py", line 610, in forward
    ret[head] = self.__getattr__(head)(x)
  File "D:\Anaconda\envs\CenterNet2\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\CenterNet2\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "D:\Anaconda\envs\CenterNet2\lib\site-packages\torch\nn\modules\module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\envs\CenterNet2\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by yearddxx01** [comment]
楼上，应该是你的显存不够用了，参数改小点

**Comment by yearddxx01** [comment]
你能发一下你训练用的什么命令吗？

**Comment by yearddxx01** [comment]
用的是dcn版本吗？

**Comment by YunLongPan** [comment]
> 用的是dcn版本吗？

您好! 问题已解决，原因是我原来用的是torch0.4版本的环境，换成torch1.2以后没有该报错问题。但不知在R-CenterNet中如何编译DCN，与原版CenterNet中的DCN文件有些区别。

**Comment by ZeroE04** [comment]
> > 用的是dcn版本吗？
> 
> 您好! 问题已解决，原因是我原来用的是torch0.4版本的环境，换成torch1.2以后没有该报错问题。但不知在R-CenterNet中如何编译DCN，与原版CenterNet中的DCN文件有些区别。

您好，R-CeneterNet编译DCN与原版保持一致，直接复制即可，我自己也是用的原版CenterNet编译的DCN。

**Comment by ustczhouyu** [comment]
请问怎么根据给定的矩形的四个顶点坐标来生成符合要求的json格式的标签，能分享代码吗？谢谢
